spring.application.name=jasperreportapi

# Oracle JDBC Configuration
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@192.168.201.125:1521/ifuatpdb}
spring.datasource.username=${DB_USERNAME:ababil}
spring.datasource.password=${DB_PASSWORD:AbabilUat2024}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
reports.directory=${REPORTS_DIRECTORY:./reports}